package com.wenge.datagroup.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrawlerListUrl<M extends BaseCrawlerListUrl<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setHomeUrlId(java.lang.Integer homeUrlId) {
		set("home_url_id", homeUrlId);
		return (M)this;
	}

	public java.lang.Integer getHomeUrlId() {
		return get("home_url_id");
	}

	public M setChannelName(java.lang.String channelName) {
		set("channel_name", channelName);
		return (M)this;
	}

	public java.lang.String getChannelName() {
		return get("channel_name");
	}

	public M setListUrl(java.lang.String listUrl) {
		set("list_url", listUrl);
		return (M)this;
	}

	public java.lang.String getListUrl() {
		return get("list_url");
	}

	public M setClusterId(java.lang.Integer clusterId) {
		set("cluster_id", clusterId);
		return (M)this;
	}

	public java.lang.Integer getClusterId() {
		return get("cluster_id");
	}

	public M setInsertTime(java.util.Date insertTime) {
		set("insert_time", insertTime);
		return (M)this;
	}

	public java.util.Date getInsertTime() {
		return get("insert_time");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public M setLastCrawlerTime(java.util.Date lastCrawlerTime) {
		set("last_crawler_time", lastCrawlerTime);
		return (M)this;
	}

	public java.util.Date getLastCrawlerTime() {
		return get("last_crawler_time");
	}

	public M setIsProxy(java.lang.Integer isProxy) {
		set("is_proxy", isProxy);
		return (M)this;
	}

	public java.lang.Integer getIsProxy() {
		return get("is_proxy");
	}

	public M setIsLogin(java.lang.Integer isLogin) {
		set("is_login", isLogin);
		return (M)this;
	}

	public java.lang.Integer getIsLogin() {
		return get("is_login");
	}

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public M setRuleId(java.lang.Integer ruleId) {
		set("rule_id", ruleId);
		return (M)this;
	}

	public java.lang.Integer getRuleId() {
		return get("rule_id");
	}

	public M setNextPageXpath(java.lang.String nextPageXpath) {
		set("next_page_xpath", nextPageXpath);
		return (M)this;
	}

	public java.lang.String getNextPageXpath() {
		return get("next_page_xpath");
	}

	public M setClickXpath(java.lang.String clickXpath) {
		set("click_xpath", clickXpath);
		return (M)this;
	}

	public java.lang.String getClickXpath() {
		return get("click_xpath");
	}

	public M setNextPageRule(java.lang.String nextPageRule) {
		set("next_page_rule", nextPageRule);
		return (M)this;
	}

	public java.lang.String getNextPageRule() {
		return get("next_page_rule");
	}

	public M setIsRender(java.lang.Integer isRender) {
		set("is_render", isRender);
		return (M)this;
	}

	public java.lang.Integer getIsRender() {
		return get("is_render");
	}

}
