package com.wenge.datagroup.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrawlerHomeUrl<M extends BaseCrawlerHomeUrl<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setSiteName(java.lang.String siteName) {
		set("site_name", siteName);
		return (M)this;
	}

	public java.lang.String getSiteName() {
		return get("site_name");
	}

	public M setHomeUrl(java.lang.String homeUrl) {
		set("home_url", homeUrl);
		return (M)this;
	}

	public java.lang.String getHomeUrl() {
		return get("home_url");
	}

	public M setIsProxy(java.lang.Integer isProxy) {
		set("is_proxy", isProxy);
		return (M)this;
	}

	public java.lang.Integer getIsProxy() {
		return get("is_proxy");
	}

	public M setIsLogin(java.lang.Integer isLogin) {
		set("is_login", isLogin);
		return (M)this;
	}

	public java.lang.Integer getIsLogin() {
		return get("is_login");
	}

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public M setInsertTime(java.util.Date insertTime) {
		set("insert_time", insertTime);
		return (M)this;
	}

	public java.util.Date getInsertTime() {
		return get("insert_time");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public M setIsRender(java.lang.Integer isRender) {
		set("is_render", isRender);
		return (M)this;
	}

	public java.lang.Integer getIsRender() {
		return get("is_render");
	}

}
