package com.wenge.datagroup.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("crawler_detail_url", "id", CrawlerDetailUrl.class);
		arp.addMapping("crawler_home_url", "id", CrawlerHomeUrl.class);
		arp.addMapping("crawler_list_url", "id", CrawlerListUrl.class);
	}
}

