package com.wenge.datagroup.model;

import com.wenge.datagroup.model.base.BaseCrawlerDetailUrl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrawlerDetailUrl extends BaseCrawlerDetailUrl<CrawlerDetailUrl> {
	public static final CrawlerDetailUrl dao = new CrawlerDetailUrl().dao();
}
