package com.wenge.datagroup.model;

import com.wenge.datagroup.model.base.BaseCrawlerHomeUrl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrawlerHomeUrl extends BaseCrawlerHomeUrl<CrawlerHomeUrl> {
	public static final CrawlerHomeUrl dao = new CrawlerHomeUrl().dao();
}
