package com.wenge.datagroup.model;

import com.wenge.datagroup.model.base.BaseCrawlerListUrl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrawlerListUrl extends BaseCrawlerListUrl<CrawlerListUrl> {
	public static final CrawlerListUrl dao = new CrawlerListUrl().dao();
}
